# Generated by Django 3.1.6 on 2021-03-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=30)),
                ('option_two', models.CharField(max_length=30)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('question_2', models.TextField()),
                ('option_2_one', models.CharField(max_length=30)),
                ('option_2_two', models.CharField(max_length=30)),
                ('option_2_one_count', models.IntegerField(default=0)),
                ('option_2_two_count', models.IntegerField(default=0)),
                ('question_3', models.TextField()),
                ('option_3_one', models.CharField(max_length=30)),
                ('option_3_two', models.CharField(max_length=30)),
                ('option_3_three', models.CharField(max_length=30)),
                ('option_3_four', models.CharField(max_length=30)),
                ('option_3_five', models.CharField(max_length=30)),
                ('option_3_one_count', models.IntegerField(default=0)),
                ('option_3_two_count', models.IntegerField(default=0)),
                ('option_3_three_count', models.IntegerField(default=0)),
                ('option_3_four_count', models.IntegerField(default=0)),
                ('option_3_five_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/%y/%m/%d')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rating.poll')),
            ],
        ),
    ]
