# Generated by Django 3.1.6 on 2021-03-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20210307_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_2_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_2_one_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_2_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_2_two_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_five',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_five_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_four',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_four_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_one_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_3_two_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question_3',
        ),
    ]
